"""Static demo seed definitions."""

from datetime import date

EMPLOYEE_DATA = [
    # (
    #     Personalnummer, Vorname, Nachname, Geb., Straße, PLZ, Stadt,
    #     Abteilung, Schichtmodell, Schicht, Team, EG, Qualifikationen
    # )
    (
        "MA-0001",
        "Thomas",
        "Hoffmann",
        date(1978, 3, 12),
        "Ruhrstraße 14",
        "44135",
        "Dortmund",
        "Instandhaltung",
        "3-Schicht",
        "Früh",
        1,
        "EG 8",
        "SPS-Programmierung, Schaltschrankbau, Elektrofachkraft",
    ),
    (
        "MA-0002",
        "Sandra",
        "Becker",
        date(1985, 7, 23),
        "Kirchweg 5",
        "44787",
        "Bochum",
        "Instandhaltung",
        "3-Schicht",
        "Spät",
        1,
        "EG 7",
        "Hydraulik, Pneumatik, Schweißen MAG",
    ),
    (
        "MA-0003",
        "Kevin",
        "Schulze",
        date(1991, 1, 8),
        "Hauptstraße 82",
        "45127",
        "Essen",
        "Instandhaltung",
        "3-Schicht",
        "Nacht",
        2,
        "EG 6",
        "Antriebstechnik, Frequenzumrichter, SPS-Basis",
    ),
    (
        "MA-0004",
        "Miriam",
        "Krause",
        date(1982, 11, 3),
        "Lindenallee 27",
        "58095",
        "Hagen",
        "Instandhaltung",
        "3-Schicht",
        "Früh",
        2,
        "EG 7",
        "Mess- und Regelungstechnik, Kalibrierung",
    ),
    (
        "MA-0005",
        "Oliver",
        "Petersen",
        date(1975, 4, 17),
        "Bahnhofstraße 3",
        "42103",
        "Wuppertal",
        "Instandhaltung",
        "2-Schicht",
        "Früh",
        3,
        "EG 9",
        "Elektrofachkraft, Betriebsmittelbau, VDE-Prüfung",
    ),
    (
        "MA-0006",
        "Fatima",
        "Yilmaz",
        date(1989, 9, 5),
        "Westfalenring 44",
        "44135",
        "Dortmund",
        "Instandhaltung",
        "2-Schicht",
        "Spät",
        3,
        "EG 6",
        "Pneumatik, Wartungsplanung, 5S-Auditor",
    ),
    (
        "MA-0007",
        "Markus",
        "Wagner",
        date(1980, 6, 30),
        "Schillerstraße 11",
        "44787",
        "Bochum",
        "Instandhaltung",
        "Tagschicht",
        "Frei",
        4,
        "EG 9",
        "Robotik, KUKA-Programmierung, Sicherheitstechnik",
    ),
    (
        "MA-0008",
        "Julia",
        "Neumann",
        date(1994, 2, 14),
        "Bergmannstraße 8",
        "45127",
        "Essen",
        "Instandhaltung",
        "3-Schicht",
        "Nacht",
        4,
        "EG 6",
        "Elektrische Prüftechnik, Messprotokoll",
    ),
    (
        "MA-0009",
        "Dirk",
        "Hartmann",
        date(1973, 8, 22),
        "Am Förderturm 17",
        "44135",
        "Dortmund",
        "Produktion",
        "3-Schicht",
        "Früh",
        1,
        "EG 6",
        "CNC-Drehen, Fräsen, Messmittelkunde",
    ),
    (
        "MA-0010",
        "Ayse",
        "Demir",
        date(1987, 12, 1),
        "Kohlenpottweg 33",
        "44787",
        "Bochum",
        "Produktion",
        "3-Schicht",
        "Spät",
        1,
        "EG 5",
        "Rüsten CNC, Erstmuster, Qualitätsprüfung",
    ),
    (
        "MA-0011",
        "Patrick",
        "Müller",
        date(1992, 5, 19),
        "Industrieweg 6",
        "45127",
        "Essen",
        "Produktion",
        "3-Schicht",
        "Nacht",
        2,
        "EG 5",
        "Spritzguss, Werkzeugwechsel, Kanban",
    ),
    (
        "MA-0012",
        "Claudia",
        "Werner",
        date(1984, 10, 7),
        "Hochofenstraße 21",
        "58095",
        "Hagen",
        "Produktion",
        "3-Schicht",
        "Früh",
        2,
        "EG 6",
        "Montagelinie, Einrichtung, Lean Basics",
    ),
    (
        "MA-0013",
        "Stefan",
        "Braun",
        date(1979, 3, 25),
        "Zechensiedlung 4",
        "42103",
        "Wuppertal",
        "Produktion",
        "3-Schicht",
        "Spät",
        3,
        "EG 5",
        "Foerderband, Staplerführerschein, Sichtkontrolle",
    ),
    (
        "MA-0014",
        "Melanie",
        "Koch",
        date(1996, 7, 11),
        "Schachtstraße 9",
        "44135",
        "Dortmund",
        "Produktion",
        "3-Schicht",
        "Nacht",
        3,
        "EG 5",
        "Verpackung, Etikettiersystem, 5S",
    ),
    (
        "MA-0015",
        "Tobias",
        "Zimmermann",
        date(1983, 1, 4),
        "Ruhrdeich 55",
        "44787",
        "Bochum",
        "Produktion",
        "Wochenendteam",
        "Früh",
        4,
        "EG 6",
        "Roboterzelle, Vakuumtechnik, Probelauf",
    ),
    (
        "MA-0016",
        "Nicole",
        "Lange",
        date(1990, 4, 28),
        "Steinkohlenallee 13",
        "45127",
        "Essen",
        "Produktion",
        "2-Schicht",
        "Früh",
        4,
        "EG 5",
        "Qualitätsprüfung, Erstmuster, SPC",
    ),
    (
        "MA-0017",
        "Andreas",
        "Schmitz",
        date(1977, 9, 16),
        "Kanalstraße 38",
        "58095",
        "Hagen",
        "Produktion",
        "2-Schicht",
        "Spät",
        5,
        "EG 6",
        "CNC-Fräsen, Messmaschinenführer, Lean",
    ),
    (
        "MA-0018",
        "Lena",
        "Wolf",
        date(1995, 11, 22),
        "Prosper-Platz 2",
        "42103",
        "Wuppertal",
        "Produktion",
        "3-Schicht",
        "Früh",
        5,
        "EG 5",
        "Montagelinie, Sichtkontrolle, Schichtübergabe",
    ),
    (
        "MA-0019",
        "Carsten",
        "Richter",
        date(1986, 6, 3),
        "Hüttenstraße 47",
        "44135",
        "Dortmund",
        "Logistik",
        "Tagschicht",
        "Frei",
        6,
        "EG 5",
        "Staplerführerschein, Kranbedienung, Lagerlogistik",
    ),
    (
        "MA-0020",
        "Sabine",
        "Klein",
        date(1981, 2, 18),
        "Am Viadukt 8",
        "44787",
        "Bochum",
        "Logistik",
        "2-Schicht",
        "Früh",
        6,
        "EG 4",
        "Wareneingang, Buchung SAP, Inventur",
    ),
    (
        "MA-0021",
        "Daniel",
        "Schäfer",
        date(1993, 8, 9),
        "Bergbaustraße 71",
        "45127",
        "Essen",
        "Logistik",
        "2-Schicht",
        "Spät",
        7,
        "EG 4",
        "Kommissionierung, Etikettierung, Versand",
    ),
    (
        "MA-0022",
        "Tanja",
        "König",
        date(1988, 12, 27),
        "Zeche-Nord-Str. 5",
        "58095",
        "Hagen",
        "Logistik",
        "Tagschicht",
        "Frei",
        7,
        "EG 5",
        "Staplerführerschein, Gefahrgutbeauftragter",
    ),
    (
        "MA-0023",
        "Michael",
        "Fischer",
        date(1976, 5, 6),
        "Gußstahlstraße 29",
        "42103",
        "Wuppertal",
        "Qualität",
        "Tagschicht",
        "Frei",
        8,
        "EG 8",
        "Qualitätsmanagement, Reklamationsbearbeitung, Auditor",
    ),
    (
        "MA-0024",
        "Kerstin",
        "Herrmann",
        date(1983, 10, 14),
        "Altenessener Str. 62",
        "45127",
        "Essen",
        "Qualität",
        "2-Schicht",
        "Früh",
        8,
        "EG 7",
        "SPC, Messmittelkunde, FMEA",
    ),
    (
        "MA-0025",
        "Jens",
        "Schwarz",
        date(1990, 3, 31),
        "Nordsternstraße 17",
        "44135",
        "Dortmund",
        "Qualität",
        "2-Schicht",
        "Spät",
        8,
        "EG 7",
        "Erstmuster, Mess- und Prüftechnik, CMM-Bedienung",
    ),
    (
        "MA-0026",
        "Petra",
        "Weiß",
        date(1978, 7, 20),
        "Victoriastraße 3",
        "44787",
        "Bochum",
        "Verwaltung",
        "Tagschicht",
        "Frei",
        9,
        "EG 8",
        "Einkauf, SAP MM, Rahmenverträge",
    ),
    (
        "MA-0027",
        "Frank",
        "Lorenz",
        date(1972, 1, 15),
        "Obere Schmidtstraße 44",
        "45127",
        "Essen",
        "Verwaltung",
        "Tagschicht",
        "Frei",
        9,
        "EG 9",
        "Kostenrechnung, Controlling, DATEV",
    ),
    (
        "MA-0028",
        "Ines",
        "Meyer",
        date(1985, 6, 8),
        "Glückaufstraße 16",
        "58095",
        "Hagen",
        "Verwaltung",
        "Tagschicht",
        "Frei",
        9,
        "EG 7",
        "Personalwesen, Entgeltabrechnung, Sozialrecht",
    ),
    (
        "MA-0029",
        "Ralf",
        "Bergmann",
        date(1981, 11, 25),
        "Lothringenstraße 9",
        "42103",
        "Wuppertal",
        "IT",
        "Tagschicht",
        "Frei",
        10,
        "EG 9",
        "Windows Server, VMware, Active Directory",
    ),
    (
        "MA-0030",
        "Sonja",
        "Brandt",
        date(1993, 4, 10),
        "Hiberniastraße 23",
        "44135",
        "Dortmund",
        "IT",
        "Tagschicht",
        "Frei",
        10,
        "EG 8",
        "Netzwerk, Firewall, WLAN-Administration",
    ),
]

# ---------------------------------------------------------------------------
# Benutzerdefinitionen (verknüpft mit Mitarbeitern via Personalnummer)
# ---------------------------------------------------------------------------
