"""initial migration

Revision ID: 1645029b9eea
Revises: 
Create Date: 2026-05-04 22:47:43.856504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1645029b9eea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'machine', ['favorite_machine_id'], ['id'])

    with op.batch_alter_table('error_entry', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'machine', ['machine_id'], ['id'])

    with op.batch_alter_table('generated_document', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'machine', ['machine_id'], ['id'])

    with op.batch_alter_table('shift_plan', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['created_by'], ['id'])

    with op.batch_alter_table('shift_plan_entry', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_unique_constraint('uq_entry_emp_day', ['plan_id', 'employee_id', 'work_date'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'employee', ['employee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('shift_plan_entry', schema=None) as batch_op:
        batch_op.drop_constraint('uq_entry_emp_day', type_='unique')
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('shift_plan', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('generated_document', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('error_entry', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
